# Generated by Django 3.2.10 on 2021-12-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_profil',
            field=models.ImageField(blank=True, null=True, upload_to='images/profils/', verbose_name='Image profil'),
        ),
    ]
