# Generated by Django 3.2.10 on 2021-12-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_like_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='like_old',
        ),
    ]
