# Generated by Django 3.2.10 on 2021-12-29 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageProfil',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachments.image')),
                ('image', models.ImageField(upload_to='images/profils/', verbose_name='Image')),
            ],
            bases=('attachments.image',),
        ),
        migrations.CreateModel(
            name='ImageTicket',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='attachments.image')),
                ('image', models.ImageField(upload_to='images/tickets/', verbose_name='Image')),
            ],
            bases=('attachments.image',),
        ),
    ]
