# Generated by Django 3.2.10 on 2022-01-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_image_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprofil',
            name='image_ptr',
        ),
        migrations.RemoveField(
            model_name='imageticket',
            name='image_ptr',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageProfil',
        ),
        migrations.DeleteModel(
            name='ImageTicket',
        ),
    ]
