# Generated by Django 3.2.10 on 2021-12-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_image_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_profil',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo de profil'),
        ),
    ]
