# Generated by Django 3.2.10 on 2021-12-29 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_auto_20211229_0959'),
        ('authentication', '0008_alter_user_image_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attachments.imageprofil', verbose_name='Photo de profil'),
        ),
    ]
