# Generated by Django 3.2.10 on 2022-01-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='time_create',
            new_name='time_created',
        ),
    ]
